version: '3.9'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ../frontend:/app
    image: infrastructure_frontend:latest

  backend:
    build:
      context: ../backend
      dockerfile: Dockerfile
    ports:
      - '81:80'
